# Generated by Django 2.0.4 on 2018-10-01 05:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Course Name')),
                ('image', models.ImageField(upload_to='course_image', verbose_name='Course Thumbnail')),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 1, 5, 55, 17, 258940, tzinfo=utc), null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('description', models.TextField(blank=True, help_text='a description of the Course', verbose_name='Course Description')),
                ('url', models.SlugField(help_text='a user friendly url', max_length=60, verbose_name='user friendly url')),
                ('course_requirements', models.TextField(blank=True, help_text='Course requirements.', verbose_name='Course requirements')),
                ('target_audience', models.TextField(blank=True, help_text='Who need this course?', verbose_name='Target Audience')),
            ],
            options={
                'verbose_name': 'CourseDetails',
                'verbose_name_plural': 'CourseDetails',
            },
        ),
        migrations.CreateModel(
            name='CourseId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='CourseId')),
            ],
            options={
                'verbose_name': 'CourseId',
                'verbose_name_plural': "CourseId's",
            },
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='courseid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.CourseId', verbose_name='CourseId'),
        ),
    ]
