# Generated by Django 2.0.4 on 2018-10-09 07:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20181009_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(max_length=100, verbose_name='Course Name')),
                ('video', models.FileField(upload_to='videos', verbose_name='Course video')),
                ('explain', models.TextField(blank=True, help_text='a description of the video', verbose_name='Video Description')),
                ('courseid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.CourseId', verbose_name='CourseId')),
            ],
            options={
                'verbose_name': 'CourseContent',
                'verbose_name_plural': 'CourseContents',
            },
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 9, 7, 42, 26, 805940, tzinfo=utc), null=True, verbose_name='Start Date'),
        ),
    ]
