# Generated by Django 2.1.2 on 2018-10-18 06:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20181015_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 18, 6, 53, 28, 645252, tzinfo=utc), null=True, verbose_name='Start Date'),
        ),
    ]
