# Generated by Django 2.0.4 on 2018-11-12 04:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20181109_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetails',
            name='ccategory',
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='category',
            field=models.CharField(choices=[('Trainocate', 'Trainocate'), ('Microsoft', 'Microsoft'), ('Cisco', 'Cisco')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='courseid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.CourseId', verbose_name='CourseId'),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 12, 4, 33, 36, 423415, tzinfo=utc), null=True, verbose_name='Start Date'),
        ),
        migrations.DeleteModel(
            name='CoursesCategory',
        ),
    ]
