# Generated by Django 2.1.3 on 2018-11-20 04:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20181112_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 20, 4, 48, 59, 243478, tzinfo=utc), null=True, verbose_name='Start Date'),
        ),
    ]
