# Generated by Django 2.1.3 on 2018-11-20 05:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20181120_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 20, 5, 23, 58, 269536, tzinfo=utc), null=True, verbose_name='Start Date'),
        ),
    ]
