# Generated by Django 2.1.3 on 2018-11-20 06:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_auto_20181120_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 20, 6, 10, 11, 61130, tzinfo=utc), null=True, verbose_name='Start Date'),
        ),
    ]
