# Generated by Django 2.1.3 on 2018-11-20 06:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_auto_20181120_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Question')),
                ('option1', models.CharField(max_length=60, verbose_name='A')),
                ('option2', models.CharField(max_length=60, verbose_name='B')),
                ('option3', models.CharField(max_length=60, verbose_name='C')),
                ('option4', models.CharField(max_length=60, verbose_name='D')),
                ('answer', models.CharField(max_length=60, verbose_name='answer')),
                ('courseid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.CourseId', verbose_name='CourseId')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 20, 6, 43, 17, 540750, tzinfo=utc), null=True, verbose_name='Start Date'),
        ),
    ]
