# Generated by Django 2.1.3 on 2018-11-20 09:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_auto_20181120_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=60, verbose_name='User')),
                ('cid', models.CharField(max_length=60, verbose_name='CourseId')),
                ('correct', models.CharField(max_length=60, verbose_name='Score')),
                ('total', models.CharField(max_length=60, verbose_name='Possible Score')),
            ],
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 20, 9, 30, 47, 807580, tzinfo=utc), null=True, verbose_name='Start Date'),
        ),
    ]
