# Generated by Django 2.1.3 on 2018-11-23 05:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_auto_20181120_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 23, 5, 30, 42, 139264, tzinfo=utc), null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 23, 5, 30, 42, 136264, tzinfo=utc), null=True, verbose_name='Start Date'),
        ),
    ]
