# Generated by Django 2.1.3 on 2018-11-23 05:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_auto_20181123_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='start_date',
        ),
        migrations.AddField(
            model_name='progress',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 23, 5, 46, 37, 174889, tzinfo=utc), null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 23, 5, 46, 37, 170889, tzinfo=utc), null=True, verbose_name='Start Date'),
        ),
    ]
