# Generated by Django 2.1.3 on 2018-11-26 07:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_auto_20181123_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 26, 7, 38, 21, 331658, tzinfo=utc), null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 26, 7, 38, 21, 334658, tzinfo=utc), null=True, verbose_name='Date'),
        ),
    ]
