# Generated by Django 2.1.3 on 2018-11-26 11:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_auto_20181126_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryt', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Categoryt')),
            ],
            options={
                'verbose_name': 'Categoryt',
                'verbose_name_plural': 'Categoriest',
            },
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 26, 11, 35, 58, 274194, tzinfo=utc), null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 26, 11, 35, 58, 277194, tzinfo=utc), null=True, verbose_name='Date'),
        ),
    ]
