# Generated by Django 2.1.3 on 2018-11-26 11:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_auto_20181126_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryt',
            name='summa',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Summa'),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 26, 11, 41, 41, 17797, tzinfo=utc), null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 26, 11, 41, 41, 20798, tzinfo=utc), null=True, verbose_name='Date'),
        ),
    ]
