# Generated by Django 2.1.3 on 2018-11-26 11:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_auto_20181126_1711'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryT',
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 26, 11, 56, 15, 609821, tzinfo=utc), null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 26, 11, 56, 15, 612821, tzinfo=utc), null=True, verbose_name='Date'),
        ),
    ]
