# Generated by Django 2.1.3 on 2018-12-04 09:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0027_auto_20181204_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 4, 9, 25, 22, 912601, tzinfo=utc), null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 4, 9, 25, 22, 915601, tzinfo=utc), null=True, verbose_name='Date'),
        ),
    ]
