(function(g){var window=this;var XEa=function(a,b){return g.Sb(a,b)},c6=function(a){g.gn(a,"zx",g.ub());
return a},d6=function(a,b,c){g.wa(c)||(c=[String(c)]);
g.kn(a.o,b,c)},YEa=function(a,b){var c=[];
g.Tk(b,function(a){try{var b=g.JD.prototype.A.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.u(b)?g.ID(b)&&c.push(a):c.push(a)},a);
return c},ZEa=function(a,b){var c=YEa(a,b);
(0,g.D)(c,function(a){g.JD.prototype.remove.call(this,a)},a)},$Ea=function(a){if(a.Md){if(a.Md.locationOverrideToken)return{locationOverrideToken:a.Md.locationOverrideToken};
if(null!=a.Md.latitudeE7&&null!=a.Md.longitudeE7)return{latitudeE7:a.Md.latitudeE7,longitudeE7:a.Md.longitudeE7}}return null},aFa=function(a,b,c,d){var e=new g.Ym(null,void 0);
a&&g.Zm(e,a);b&&g.$m(e,b);c&&g.an(e,c);d&&g.bn(e,d);return e},bFa=function(a){g.tG[a]&&(a=g.tG[a],(0,g.D)(a,function(a){g.rG[a]&&delete g.rG[a]}),a.length=0)},cFa=function(a){var b=g.qG();
if(b)if(b.clear(a),a)bFa(a);else for(var c in g.tG)bFa(c)},e6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.B=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.Sm;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",dFa(this,a.capabilities||""),eFa(this,a.experiments||""),this.A=a.remoteControllerUrl||"",
this.o=a.localChannelEncryptionKey||"")},dFa=function(a,b){a.capabilities.clear();
(0,g.Yd)(b.split(","),g.Ca(XEa,fFa)).forEach(function(b){a.capabilities.add(b)})},eFa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},f6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},g6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},gFa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},hFa=function(a){return new f6(a)},iFa=function(a){return g.wa(a)?(0,g.J)(a,hFa):[]},h6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},i6=function(a){return g.wa(a)?"["+(0,g.J)(a,h6).join(",")+"]":"null"},j6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},jFa=function(a){return(0,g.J)(a,function(a){return{key:a.id,
name:a.name}})},k6=function(a,b){return g.Ha(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},l6=function(a,b){return g.Ha(a,function(a){return g6(a,b)})},kFa=function(){var a=(0,g.CH)();
a&&ZEa(a,a.o.fe(!0))},m6=function(){var a=g.FH("yt-remote-connected-devices")||[];
g.db(a);return a},lFa=function(a){if(g.Na(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.J)(a,function(a,b){return 0==b?a:a.substring(c.length)})},mFa=function(a){g.EH("yt-remote-connected-devices",a,86400)},o6=function(){if(n6)return n6;
var a=g.FH("yt-remote-device-id");a||(a=j6(),g.EH("yt-remote-device-id",a,31536E3));for(var b=m6(),c=1,d=a;g.Ma(b,d);)c++,d=a+"#"+c;return n6=d},p6=function(){var a=m6(),b=o6();
g.Ma(a,b);g.HH()&&g.fb(a,b);a=lFa(a);if(g.Na(a))try{g.aH("remote_sid")}catch(c){}else try{g.$G("remote_sid",a.join(","),-1)}catch(c){}},nFa=function(){return g.FH("yt-remote-session-browser-channel")},oFa=function(){return g.FH("yt-remote-local-screens")||[]},pFa=function(){g.EH("yt-remote-lounge-token-expiration",!0,86400)},qFa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.J)(oFa(),function(a){return a.loungeToken}),c=(0,g.J)(a,function(a){return a.loungeToken});
(0,g.Gm)(c,function(a){return!g.Ma(b,a)})&&pFa();
g.EH("yt-remote-local-screens",a,31536E3)},rFa=function(a,b){g.EH("yt-remote-session-browser-channel",a);
g.EH("yt-remote-session-screen-id",b);var c=m6(),d=o6();g.Ma(c,d)||c.push(d);mFa(c);p6()},q6=function(a){a||(g.GH("yt-remote-session-screen-id"),g.GH("yt-remote-session-video-id"));
p6();a=m6();g.Sa(a,o6());mFa(a)},sFa=function(){if(!r6){var a=g.UD();
a&&(r6=new g.DD(a))}return r6?!!r6.get("yt-remote-use-staging-server"):!1},tFa=function(){var a=window.document.createElement("a");
g.id(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.yb(a)},uFa=function(a,b,c){c=void 0===c?null:c;
var d=g.Rd("SCRIPT");d.id=a;d.onload=function(){b&&(0,window.setTimeout)(b,0)};
d.onreadystatechange=function(){switch(d.readyState){case "loaded":case "complete":d.onload()}};
c&&d.setAttribute("nonce",c);g.kd(d,g.pe("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));a=window.document.getElementsByTagName("head")[0]||window.document.body;a.insertBefore(d,a.firstChild);return d},vFa=function(a){a=void 0===a?null:a;
var b=tFa(),c=window.document.getElementById(b),d=c&&g.AF(c,"loaded");d||c&&!d||(c=uFa(b,function(){g.AF(c,"loaded")||(g.zF(c,"loaded","true"),g.xG(b),g.zE(g.Ca(cFa,b),0))},a))},wFa=function(){var a=void 0===a?null:a;
window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):vFa(a)},s6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},xFa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},t6=function(a){a.length?yFa(a.shift(),function(){t6(a)}):u6()},zFa=function(a){return"chrome-extension://"+a+v6},yFa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},w6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},u6=function(){var a=xFa();
a&&a(!1,"No cast extension found")},x6=function(){if(AFa){var a=2,b=xFa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;yFa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",u6,c)}},BFa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(x6(),a({command:"cast.sender.init"}))},CFa=function(){x6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);t6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+v6,"//www.gstatic.com/eureka/clank"+v6])},y6=function(a,b,c){g.M.call(this);
this.F=null!=c?(0,g.B)(a,c):a;this.Dd=b;this.D=(0,g.B)(this.xL,this);this.o=!1;this.A=0;this.B=this.Ga=null;this.C=[]},z6=function(){},A6=function(a,b,c,d){this.o=a;
this.B=b;this.G=c;this.F=d||1;this.C=45E3;this.Y=new g.on(this);this.A=new g.Cg;this.A.setInterval(250)},EFa=function(a,b,c){a.Zj=1;
a.yh=c6(b.clone());a.lj=c;a.D=!0;DFa(a,null)},B6=function(a,b,c,d,e){a.Zj=1;
a.yh=c6(b.clone());a.lj=null;a.D=c;e&&(a.QF=!1);DFa(a,d)},DFa=function(a,b){a.Uk=(0,g.H)();
C6(a);a.Zh=a.yh.clone();d6(a.Zh,"t",a.F);a.On=0;a.Vc=a.o.jt(a.o.Fn()?b:null);0<a.Xt&&(a.Rq=new g.zl((0,g.B)(a.lH,a,a.Vc),a.Xt));a.Y.W(a.Vc,"readystatechange",a.bX);var c=a.Ii?g.bc(a.Ii):{};a.lj?(a.Gr="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Vc.send(a.Zh,a.Gr,a.lj,c)):(a.Gr="GET",a.QF&&!g.Ld&&(c.Connection="close"),a.Vc.send(a.Zh,a.Gr,null,c));a.o.If(1)},HFa=function(a,b,c){for(var d=!0;!a.ri&&a.On<c.length;){var e=FFa(a,c);
if(e==D6){4==b&&(a.zh=4,E6(15),d=!1);break}else if(e==GFa){a.zh=4;E6(16);d=!1;break}else F6(a,e)}4==b&&0==c.length&&(a.zh=1,E6(17),d=!1);a.Pf=a.Pf&&d;d||(G6(a),H6(a))},FFa=function(a,b){var c=a.On,d=b.indexOf("\n",c);
if(-1==d)return D6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return GFa;d+=1;if(d+c>b.length)return D6;var e=b.substr(d,c);a.On=d+c;return e},JFa=function(a,b){a.Uk=(0,g.H)();
C6(a);var c=b?window.location.hostname:"";a.Zh=a.yh.clone();g.gn(a.Zh,"DOMAIN",c);g.gn(a.Zh,"t",a.F);try{a.Qf=new window.ActiveXObject("htmlfile")}catch(n){G6(a);a.zh=7;E6(22);H6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in I6)k=I6[l];else if(l in IFa)k=I6[l]=IFa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=I6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.ld(g.Ac("b/12014412"),d+"</body></html>");a.Qf.open();a.Qf.write(g.bd(c));a.Qf.close();a.Qf.parentWindow.m=(0,g.B)(a.eW,a);a.Qf.parentWindow.d=(0,g.B)(a.YE,a,!0);a.Qf.parentWindow.rpcClose=(0,g.B)(a.YE,a,!1);c=a.Qf.createElement("DIV");a.Qf.parentWindow.document.body.appendChild(c);d=g.Pc(a.Zh.toString());d=g.nb(g.Mc(d));d=g.ld(g.Ac("b/12014412"),'<iframe src="'+d+'"></iframe>');g.hd(c,g.bd(d));a.o.If(1)},
C6=function(a){a.Wx=(0,g.H)()+a.C;
KFa(a,a.C)},KFa=function(a,b){if(null!=a.ql)throw Error("WatchDog timer not null");
a.ql=J6((0,g.B)(a.uW,a),b)},K6=function(a){a.ql&&(g.x.clearTimeout(a.ql),a.ql=null)},H6=function(a){a.o.fB()||a.ri||a.o.Bq(a)},G6=function(a){K6(a);
g.nf(a.Rq);a.Rq=null;a.A.stop();g.un(a.Y);if(a.Vc){var b=a.Vc;a.Vc=null;b.abort();b.dispose()}a.Qf&&(a.Qf=null)},F6=function(a,b){try{a.o.QE(a,b),a.o.If(4)}catch(c){}},MFa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;LFa(a,b,function(e){e?c(!0):g.x.setTimeout(function(){MFa(a,b,c,d,f)},f)})}},LFa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{L6(d),c(!0)}catch(e){}};
d.onerror=function(){try{L6(d),c(!1)}catch(e){}};
d.onabort=function(){try{L6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{L6(d),c(!1)}catch(e){}};
g.x.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},L6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},NFa=function(a){this.o=a;
this.A=new z6},OFa=function(a){var b=M6(a.o,a.yl,"/mail/images/cleardot.gif");
c6(b);MFa(b.toString(),5E3,(0,g.B)(a.zK,a),3,2E3);a.If(1)},O6=function(a){var b=a.o.J;
if(null!=b)E6(5),b?(E6(11),N6(a.o,a,!1)):(E6(12),N6(a.o,a,!0));else if(a.Je=new A6(a,void 0,void 0,void 0),a.Je.Ii=a.Vt,b=a.o,b=M6(b,b.Fn()?a.lm:null,a.Wt),E6(5),!g.Jd||g.sc(10))d6(b,"TYPE","xmlhttp"),B6(a.Je,b,!1,a.lm,!1);else{d6(b,"TYPE","html");var c=a.Je;a=!!a.lm;c.Zj=3;c.yh=c6(b.clone());JFa(c,a)}},P6=function(a,b,c){this.o=1;
this.A=[];this.C=[];this.D=new z6;this.H=a||null;this.J=null!=b?b:null;this.F=c||!1},PFa=function(a,b){this.o=a;
this.map=b;this.context=null},QFa=function(a){g.pf.call(this,"statevent",a)},RFa=function(a,b){g.pf.call(this,"timingevent",a);
this.size=b},SFa=function(a){g.pf.call(this,"serverreachability",a)},VFa=function(a){TFa(a);
if(3==a.o){var b=a.ln++,c=a.lp.clone();g.gn(c,"SID",a.B);g.gn(c,"RID",b);g.gn(c,"TYPE","terminate");Q6(a,c);b=new A6(a,a.B,b,void 0);b.Zj=2;b.yh=c6(c.clone());(new window.Image).src=b.yh;b.Uk=(0,g.H)();C6(b)}UFa(a)},WFa=function(a){a.XK(1,0);
a.lp=M6(a,null,a.Ut);R6(a)},TFa=function(a){a.oh&&(a.oh.abort(),a.oh=null);
a.yc&&(a.yc.cancel(),a.yc=null);a.Cg&&(g.x.clearTimeout(a.Cg),a.Cg=null);S6(a);a.ke&&(a.ke.cancel(),a.ke=null);a.sh&&(g.x.clearTimeout(a.sh),a.sh=null)},XFa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new PFa(a.RR++,b));2!=a.o&&3!=a.o||R6(a)},R6=function(a){a.ke||a.sh||(a.sh=J6((0,g.B)(a.WE,a),0),a.Pj=0)},ZFa=function(a,b){if(1==a.o){if(!b){a.ln=Math.floor(1E5*Math.random());
var c=a.ln++,d=new A6(a,"",c,void 0);d.Ii=null;var e=T6(a),f=a.lp.clone();g.gn(f,"RID",c);g.gn(f,"CVER","1");Q6(a,f);EFa(d,f,e);a.ke=d;a.o=2}}else 3==a.o&&(b?YFa(a,b):0==a.A.length||a.ke||YFa(a))},YFa=function(a,b){if(b)if(6<a.ti){a.A=a.C.concat(a.A);
a.C.length=0;var c=a.ln-1;var d=T6(a)}else c=b.G,d=b.lj;else c=a.ln++,d=T6(a);var e=a.lp.clone();g.gn(e,"SID",a.B);g.gn(e,"RID",c);g.gn(e,"AID",a.sk);Q6(a,e);c=new A6(a,a.B,c,a.Pj+1);c.Ii=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.ke=c;EFa(c,e,d)},Q6=function(a,b){if(a.Cd){var c=a.Cd.NA();
c&&g.Gb(c,function(a,c){g.gn(b,c,a)})}},T6=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.ti&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.ti?e:f-d;try{g.Gb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.C=a.C.concat(a.A.splice(0,b));
return c.join("&")},$Fa=function(a){a.yc||a.Cg||(a.G=1,a.Cg=J6((0,g.B)(a.VE,a),0),a.Ej=0)},U6=function(a){if(a.yc||a.Cg||3<=a.Ej)return!1;
a.G++;a.Cg=J6((0,g.B)(a.VE,a),aGa(a,a.Ej));a.Ej++;return!0},N6=function(a,b,c){a.Dr=c;
a.cg=b.Og;a.F||WFa(a)},S6=function(a){null!=a.wi&&(g.x.clearTimeout(a.wi),a.wi=null)},aGa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},V6=function(a,b){if(2==b||9==b){var c=null;
a.Cd&&(c=null);var d=(0,g.B)(a.QX,a);c||(c=new g.Ym("//www.google.com/images/cleardot.gif"),c6(c));LFa(c.toString(),1E4,d)}else E6(2);bGa(a,b)},bGa=function(a,b){a.o=0;
a.Cd&&a.Cd.Pz(b);UFa(a);TFa(a)},UFa=function(a){a.o=0;
a.cg=-1;if(a.Cd)if(0==a.C.length&&0==a.A.length)a.Cd.Qs();else{g.Va(a.C);var b=g.Va(a.A);a.C.length=0;a.A.length=0;a.Cd.Qs(b)}},M6=function(a,b,c){var d=g.hn(c);
if(""!=d.A)b&&g.$m(d,b+"."+d.A),g.an(d,d.D);else{var e=window.location;d=aFa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Ol&&g.Gb(a.Ol,function(a,b){g.gn(d,b,a)});
g.gn(d,"VER",a.ti);Q6(a,d);return d},J6=function(a,b){if(!g.ya(a))throw Error("Fn must not be null and must be a function");
return g.x.setTimeout(function(){a()},b)},E6=function(a){W6.dispatchEvent(new QFa(W6,a))},cGa=function(){},dGa=function(a,b){this.action=a;
this.params=b||{}},X6=function(a,b){g.M.call(this);
this.o=new g.Fu(this.VV,0,this);g.O(this,this.o);this.Dd=5E3;this.A=0;if(g.ya(a))b&&(a=(0,g.B)(a,b));else if(a&&g.ya(a.handleEvent))a=(0,g.B)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},Y6=function(a,b,c){this.L=a;
this.F=b;this.B=new g.CD;this.A=new X6(this.vY,this);this.o=this.ib=null;this.K=!1;this.D=null;this.J="";this.H=this.C=0;this.G=[];this.M=c||!1},eGa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.Dr,sessionId:a.o.B,arrayId:a.o.sk}},fGa=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&ZFa(a.o),VFa(a.o));a.H=0},Z6=function(a){return!!a.o&&3==a.o.o},gGa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},$6=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||window.document.location.href;var b=g.Rg(a)||"";b&&(this.port=":"+b);this.domain=g.Qg(a)||"";a=g.Eb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.xb(a,"10.0")&&(this.A=!1))},a7=function(a,b){var c=a.o;
if(g.u(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.$g(c+b,{})},b7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ca(a.C,d,!0),onError:g.Ca(a.B,e),Id:g.Ca(a.D,e)};c&&(a.Tb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.QE(b,a)},kGa=function(){var a=hGa;
iGa();c7.push(a);jGa(c7)},d7=function(a,b){iGa();
var c=c7,d=lGa(a,String(b));g.Na(c)?mGa(d):(jGa(c),(0,g.D)(c,function(a){a(d)}))},iGa=function(){c7||(c7=g.y("yt.mdx.remote.debug.handlers_")||[],g.ta("yt.mdx.remote.debug.handlers_",c7,void 0))},mGa=function(a){var b=(e7+1)%50;
e7=b;f7[b]=a;g7||(g7=49==b)},jGa=function(a){var b=f7;
if(b[0]){var c=e7,d=g7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.D)(a,function(a){a(e)})}while(d!=c);
f7=Array(50);e7=-1;g7=!1}},lGa=function(a,b){var c=((0,g.H)()-nGa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},h7=function(a){g.hG.call(this);
this.G=a;this.o=[]},oGa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},pGa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.Yd)(a.o,function(a){return!!k6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=oGa(a,b[d])||c;return c},qGa=function(a,b){var c=a.o.length;
a.o=(0,g.Yd)(a.o,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.o.length<c},i7=function(a,b,c,d){g.hG.call(this);
this.F=a;this.D=b;this.B=c;this.C=d;this.A=0;this.o=null;this.Ga=window.NaN},k7=function(a){h7.call(this,"LocalScreenService");
this.B=a;this.A=window.NaN;j7(this);this.info("Initializing with "+i6(this.o))},rGa=function(a){if(a.o.length){var b=(0,g.J)(a.o,function(a){return a.id}),c=a7(a.B,"/pairing/get_lounge_token_batch");
b7(a.B,c,{screen_ids:b.join(",")},(0,g.B)(a.LL,a),(0,g.B)(a.KL,a))}},j7=function(a){var b=iFa(oFa());
b=(0,g.Yd)(b,function(a){return!a.uuid});
return pGa(a,b)},l7=function(a,b){qFa((0,g.J)(a.o,gFa));
b&&pFa()},n7=function(a,b){g.hG.call(this);
this.F=b;var c=g.FH("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Ma(c,l)}this.o=d;this.D=a;this.B=this.C=window.NaN;this.A=null;m7("Initialized with "+g.Ig(this.o))},sGa=function(a,b,c){var d=a7(a.D,"/pairing/get_screen_availability");
b7(a.D,d,{lounge_token:b.token},(0,g.B)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.B)(function(){c(!1)},a))},o7=function(a,b){a:if(g.Mb(b)!=g.Mb(a.o))var c=!1;
else{c=g.Pb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(m7("Updated online screens: "+g.Ig(a.o)),a.o=b,a.V("screenChange"));tGa(a)},p7=function(a){(0,window.isNaN)(a.B)||g.BE(a.B);
a.B=g.zE((0,g.B)(a.Uw,a),0<a.C&&a.C<(0,g.H)()?2E4:1E4)},m7=function(a){d7("OnlineScreenService",a)},uGa=function(a){var b={};
(0,g.D)(a.F(),function(a){a.token?b[a.token]=a.id:this.sc("Requesting availability of screen w/o lounge token.")});
return b},tGa=function(a){a=g.Pb(g.Hb(a.o,function(a){return a}));
g.db(a);a.length?g.EH("yt-remote-online-screen-ids",a.join(","),60):g.GH("yt-remote-online-screen-ids")},q7=function(a){h7.call(this,"ScreenService");
this.F=a;this.A=this.B=null;this.C=[];this.D={};vGa(this)},xGa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.De();if(k=(c?l6(k,c):null)||l6(k,b)){k.uuid=b;var l=r7(a,k);sGa(a.A,l,function(a){e(a?l:null)})}else c?wGa(a,c,(0,g.B)(function(a){var f=r7(this,new f6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));sGa(this.A,f,function(a){e(a?f:null)})},a),f):e(null)},yGa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},wGa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Tb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.QE(a7(a.F,"/pairing/get_lounge_token_batch"),e)},zGa=function(a){a.o=a.B.De();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+i6(a.o))},vGa=function(a){s7(a);
a.B=new k7(a.F);a.B.subscribe("screenChange",(0,g.B)(a.ZL,a));zGa(a);a.C=iFa(g.FH("yt-remote-automatic-screen-cache")||[]);s7(a);a.info("Initializing automatic screens: "+i6(a.C));a.A=new n7(a.F,(0,g.B)(a.De,a,!0));a.A.subscribe("screenChange",(0,g.B)(function(){this.V("onlineScreenChange")},a))},r7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=l6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.EH("yt-remote-automatic-screen-cache",(0,g.J)(a.C,gFa)));s7(a);a.D[b.uuid]=b.id;g.EH("yt-remote-device-id-map",a.D,31536E3);return b},s7=function(a){a.D=g.FH("yt-remote-device-id-map")||{}},t7=function(a,b,c){g.hG.call(this);
this.M=c;this.J=a;this.A=b;this.B=null},u7=function(a,b){d7(a.M,b)},v7=function(a,b){t7.call(this,a,b,"CastSession");
this.o=null;this.C=0;this.F=(0,g.B)(this.BY,this);this.D=(0,g.B)(this.HW,this);this.C=g.zE((0,g.B)(function(){AGa(this,null)},this),12E4)},BGa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Ig(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.A,(0,g.B)(function(){u7(this,"Failed to send message: getMdxSessionStatus.")},a)):u7(a,"Sending yt message without session: "+g.Ig(b))},AGa=function(a,b){g.BE(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.B||a.B.id!=b){var c=(0,g.B)(a.Cq,a),d=(0,g.B)(a.Ie,a);a.VA(b,c,d,5)}}else a.Ie(Error("Waiting for session status timed out."))},w7=function(a,b,c){t7.call(this,a,b,"DialSession");
this.C=this.H=null;this.K="";this.O=c;this.D=null;this.G=g.A;this.F=window.NaN;this.L=(0,g.B)(this.EY,this);this.o=g.A},CGa=function(a){a.o=a.J.tH(a.K,a.A.label,a.A.friendlyName,(0,g.B)(function(a){this.o=g.A;
this.Cq(a)},a),(0,g.B)(function(a){this.o=g.A;
this.Ie(a)},a))},DGa=function(a){var b={};
b.pairingCode=a.K;b.theme=a.O;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}sFa()&&(b.env_useStageMdx=1);return g.Yg(b)},x7=function(a,b){t7.call(this,a,b,"ManualSession");
this.o=g.zE((0,g.B)(this.uk,this,null),150)},y7=function(a,b,c,d){g.hG.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.B=[];this.C=(0,g.B)(this.hV,this)},EGa=function(a,b){return b?g.Ha(a.B,function(a){return g6(b,a.label)},a):null},z7=function(a){d7("Controller",a)},hGa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},A7=function(a){return a.D||!!a.B.length||!!a.o},B7=function(a,b,c){b!=a.o&&(g.nf(a.o),(a.o=b)?(c?a.V("yt-remote-cast2-receiver-resumed",b.A):a.V("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.B)(a.TE,a,b)),b.B?a.V("yt-remote-cast2-session-change",b.B):c&&a.o.uk(null)):a.V("yt-remote-cast2-session-change",null))},FGa=function(a){var b=a.A.sH(),c=a.o&&a.o.A;
a=(0,g.J)(b,function(a){c&&g6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=EGa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},LGa=function(a,b,c,d,e,f,k){GGa()?HGa(b,e,f,k)&&(D7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?IGa(a,c):(window.__onGCastApiAvailable=function(b,d){b?IGa(a,c):(E7("Failed to load cast API: "+d),F7(!1),D7(!1),g.GH("yt-remote-cast-available"),g.GH("yt-remote-cast-receiver"),JGa(),
c(!1))},d?wFa():w6("CriOS")?BFa():w6("Android")&&w6("Chrome/")&&window.navigator.presentation?CFa():window.chrome&&window.navigator.presentation&&!w6("Edge")?(x6(),t6(KGa.map(zFa))):u6())):C7("Cannot initialize because not running Chrome")},JGa=function(){C7("dispose");
var a=G7();a&&a.dispose();g.ta("yt.mdx.remote.cloudview.instance_",null,void 0);MGa(!1);g.vG(H7);H7.length=0},I7=function(){return!!g.FH("yt-remote-cast-installed")},NGa=function(){var a=g.FH("yt-remote-cast-receiver");
return a?a.friendlyName:null},OGa=function(){C7("clearCurrentReceiver");
g.GH("yt-remote-cast-receiver")},PGa=function(){return I7()?G7()?G7().getCastSession():(E7("getCastSelector: Cast is not initialized."),null):(E7("getCastSelector: Cast API is not installed!"),null)},K7=function(){I7()?G7()?J7()?(C7("Requesting cast selector."),G7().requestSession()):(C7("Wait for cast API to be ready to request the session."),H7.push(g.uG("yt-remote-cast2-api-ready",K7))):E7("requestCastSelector: Cast is not initialized."):E7("requestCastSelector: Cast API is not installed!")},L7=
function(a,b){J7()?G7().setConnectedScreenStatus(a,b):E7("setConnectedScreenStatus called before ready.")},GGa=function(){var a=0<=g.Eb.search(/ (CrMo|Chrome|CriOS)\//);
return g.QI||a},QGa=function(a,b){G7().init(a,b)},HGa=function(a,b,c,d){var e=!1;
G7()||(a=new y7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.EH("yt-remote-cast-available",a);g.yG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){C7("onReceiverSelected: "+a.friendlyName);
g.EH("yt-remote-cast-receiver",a);g.yG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){C7("onReceiverResumed: "+a.friendlyName);
g.EH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){C7("onSessionChange: "+h6(a));
a||g.GH("yt-remote-cast-receiver");g.yG("yt-remote-cast2-session-change",a)}),g.ta("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
C7("cloudview.createSingleton_: "+e);return e},G7=function(){return g.y("yt.mdx.remote.cloudview.instance_")},IGa=function(a,b){F7(!0);
D7(!1);QGa(a,function(a){a?(MGa(!0),g.xG("yt-remote-cast2-api-ready")):(E7("Failed to initialize cast API."),F7(!1),g.GH("yt-remote-cast-available"),g.GH("yt-remote-cast-receiver"),JGa());b(a)})},C7=function(a){d7("cloudview",a)},E7=function(a){d7("cloudview",a)},F7=function(a){C7("setCastInstalled_ "+a);
g.EH("yt-remote-cast-installed",a)},J7=function(){return!!g.y("yt.mdx.remote.cloudview.apiReady_")},MGa=function(a){C7("setApiReady_ "+a);
g.ta("yt.mdx.remote.cloudview.apiReady_",a,void 0)},D7=function(a){g.ta("yt.mdx.remote.cloudview.initializing_",a,void 0)},M7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.gg=!1;this.J=this.H=this.A=this.C=0;this.B=window.NaN;this.D=!1;this.reset(a)},N7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.gg=!1;a.hasNext=!1;a.G=0;a.F=(0,g.H)();a.C=0;a.A=0;a.H=0;a.J=0;a.B=window.NaN;a.D=!1},O7=function(a){return a.sb()?((0,g.H)()-a.F)/1E3:0},P7=function(a,b){a.G=b;
a.F=(0,g.H)()},Q7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.H)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},R7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&N7(a)},S7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.o);b.hasPrevious=a.gg;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.C;b.seekableEnd=a.A;b.duration=a.H;b.loadedTime=a.J;b.liveIngestionTime=a.B;return b},U7=function(a,b){g.hG.call(this);
this.o=0;this.C=a;this.F=[];this.D=new g.SC;this.B=this.A=null;this.J=(0,g.B)(this.AS,this);this.G=(0,g.B)(this.pn,this);this.H=(0,g.B)(this.zS,this);this.K=(0,g.B)(this.NS,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.gy,this),RGa(this))):c=3;0!=c&&(b?this.gy(c):g.zE((0,g.B)(function(){this.gy(c)},this),0));
var d=PGa();d&&T7(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},V7=function(a){return new M7(a.C.getPlayerContextData())},RGa=function(a){(0,g.D)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.F.push(this.C.subscribe(a,g.Ca(this.cV,a),this))},a)},SGa=function(a){(0,g.D)(a.F,function(a){this.C.unsubscribeByKey(a)},a);
a.F.length=0},W7=function(a,b){50>a.D.zc()&&g.UC(a.D,b)},Y7=function(a,b,c){var d=V7(a);
P7(d,c);-1E3!=d.playerState&&(d.playerState=b);X7(a,d)},Z7=function(a,b,c){a.C.sendMessage(b,c)},X7=function(a,b){SGa(a);
a.C.setPlayerContextData(S7(b));RGa(a)},T7=function(a,b){a.B&&(a.B.removeUpdateListener(a.J),a.B.removeMediaListener(a.G),a.pn(null));
a.B=b;a.B&&(d7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.J),a.B.addMediaListener(a.G),a.B.media.length&&a.pn(a.B.media[0]))},TGa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=V7(a);b.contentId!=d.videoId&&d7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;P7(d,a.A.getEstimatedTime());X7(a,d)}else d7("CP","No cast media video. Ignoring state update.")},$7=function(a,b,c){return(0,g.B)(function(a){this.sc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.sc("Retrying "+b+" using MDx browser channel."),Z7(this,b,c))},a)},a8=function(a,b,c){g.hG.call(this);
this.D=window.NaN;this.O=!1;this.K=this.J=this.L=this.M=window.NaN;this.U=[];this.C=this.G=this.B=this.jb=this.o=null;this.ra=a;this.U.push(g.RF(window,"beforeunload",(0,g.B)(this.BL,this)));this.A=[];this.jb=new M7;this.ba=b.id;this.o=UGa(this,c);this.o.subscribe("handlerOpened",this.ES,this);this.o.subscribe("handlerClosed",this.BS,this);this.o.subscribe("handlerError",this.CS,this);this.o.subscribe("handlerMessage",this.DS,this);gGa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.jb.videoId;g.HH()&&g.EH("yt-remote-session-video-id",a)},this)},b8=function(a){d7("conn",a)},UGa=function(a,b){return new Y6(a7(a.ra,"/bc"),b)},c8=function(a,b){a.V("proxyStateChange",b)},VGa=function(a){a.D=g.zE((0,g.B)(function(){b8("Connecting timeout");
this.F(1)},a),2E4)},d8=function(a){g.BE(a.D);
a.D=window.NaN},e8=function(a){g.BE(a.M);
a.M=window.NaN},WGa=function(a){f8(a);
a.L=g.zE((0,g.B)(function(){g8(this,"getNowPlaying")},a),2E4)},f8=function(a){g.BE(a.L);
a.L=window.NaN},YGa=function(a,b){b&&(d8(a),e8(a));
b==(Z6(a.o)&&(0,window.isNaN)(a.D))?b&&(c8(a,1),g8(a,"getSubtitlesTrack")):b?(a.Z()&&a.jb.reset(),c8(a,1),g8(a,"getNowPlaying"),XGa(a)):a.F(1)},ZGa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.jb.videoId&&(g.Xb(b.params)?a.jb.o=null:a.jb.o=b.params,a.V("remotePlayerChange"))},$Ga=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.jb.listId=b.params.listId||a.jb.listId;R7(a.jb,c,d);a.V("remoteQueueChange")},bHa=function(a,b){b.params=b.params||{};
$Ga(a,b);aHa(a,b);a.V("autoplayDismissed")},aHa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
P7(a.jb,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.jb.playerState&&(c=-1E3);a.jb.playerState=c;c=Number(b.params.loadedTime);a.jb.J=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.jb.H=(0,window.isNaN)(c)?0:c;c=a.jb;var d=Number(b.params.liveIngestionTime);c.B=d;c.D=(0,window.isNaN)(d)?!1:!0;c=a.jb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=(0,window.isNaN)(d)?0:d;c.A=(0,window.isNaN)(e)?0:
e;1==a.jb.playerState?WGa(a):f8(a);a.V("remotePlayerChange")},cHa=function(a,b){if(-1E3!=a.jb.playerState){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.jb.playerState=c;c=(0,window.parseInt)(b.params.currentTime,10);P7(a.jb,(0,window.isNaN)(c)?0:c);a.V("remotePlayerChange")}},dHa=function(a,b){var c="true"==b.params.muted;
a.jb.volume=(0,window.parseInt)(b.params.volume,10);a.jb.muted=c;a.V("remotePlayerChange")},eHa=function(a,b){a.G=b.params.videoId;
a.V("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},fHa=function(a,b){var c="true"==b.params.hasNext;
a.jb.gg="true"==b.params.hasPrevious;a.jb.hasNext=c;a.V("previousNextChange")},XGa=function(a){g.BE(a.K);
a.K=g.zE((0,g.B)(a.F,a,1),864E5)},g8=function(a,b,c){c?b8("Sending: action="+b+", params="+g.Ig(c)):b8("Sending: action="+b);
a.o.sendMessage(b,c)},h8=function(a){h7.call(this,"ScreenServiceProxy");
this.md=a;this.A=[];this.A.push(this.md.$_s("screenChange",(0,g.B)(this.zY,this)));this.A.push(this.md.$_s("onlineScreenChange",(0,g.B)(this.BU,this)))},kHa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.oE("MDX_CONFIG")||b;kFa();p6();i8||(i8=new $6(b?b.loungeApiHost:void 0),sFa()&&(i8.o="/api/loungedev"));j8||(j8=g.y("yt.mdx.remote.deferredProxies_")||[],g.ta("yt.mdx.remote.deferredProxies_",j8,void 0));gHa();var c=k8();if(!c){var d=new q7(i8);g.ta("yt.mdx.remote.screenService_",d,void 0);c=k8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);LGa(a,d,function(a){a?l8()&&L7(l8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.yG("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.y("yt.mdx.remote.initialized_")&&(g.ta("yt.mdx.remote.initialized_",!0,void 0),m8("Initializing: "+g.Ig(b)),n8.push(g.uG("yt-remote-cast2-availability-change",function(){g.yG("yt-remote-receiver-availability-change")})),n8.push(g.uG("yt-remote-cast2-receiver-selected",function(){o8(null);
g.yG("yt-remote-auto-connect","cast-selector-receiver")})),n8.push(g.uG("yt-remote-cast2-receiver-resumed",function(){g.yG("yt-remote-receiver-resumed","cast-selector-receiver")})),n8.push(g.uG("yt-remote-cast2-session-change",hHa)),n8.push(g.uG("yt-remote-connection-change",function(a){a?L7(l8(),"YouTube TV"):p8()||(L7(null,null),OGa())})),a=q8(),b.isAuto&&(a.id+="#dial"),g.wE("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),m8(" -- with channel params: "+
g.Ig(a)),iHa(a),c.start(),l8()||jHa())},mHa=function(){var a=lHa();
I7()&&g.FH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},lHa=function(){var a=k8().md.$_gos();
var b=r8();b&&s8()&&(k6(a,b)||a.push(b));return jFa(a)},t8=function(){var a=nHa();
!a&&I7()&&NGa()&&(a={key:"cast-selector-receiver",name:NGa()});return a},nHa=function(){var a=lHa(),b=r8();
b||(b=p8());return g.Ha(a,function(a){return b&&g6(b,a.key)?!0:!1})},r8=function(){var a=l8();
if(!a)return null;var b=k8().De();return l6(b,a)},hHa=function(a){m8("remote.onCastSessionChange_: "+h6(a));
if(a){var b=r8();b&&b.id==a.id?L7(b.id,"YouTube TV"):(b&&u8(),v8(a,1))}else s8()&&u8()},u8=function(){J7()?G7().stopSession():E7("stopSession called before API ready.");
var a=s8();a&&(a.disconnect(1),w8(null))},x8=function(){var a=s8();
return!!a&&3!=a.getProxyState()},m8=function(a){d7("remote",a)},k8=function(){if(!y8){var a=g.y("yt.mdx.remote.screenService_");
y8=a?new h8(a):null}return y8},l8=function(){return g.y("yt.mdx.remote.currentScreenId_")},oHa=function(a){g.ta("yt.mdx.remote.currentScreenId_",a,void 0)},pHa=function(){return g.y("yt.mdx.remote.connectData_")},o8=function(a){g.ta("yt.mdx.remote.connectData_",a,void 0)},s8=function(){return g.y("yt.mdx.remote.connection_")},w8=function(a){var b=s8();
o8(null);a||oHa("");g.ta("yt.mdx.remote.connection_",a,void 0);j8&&((0,g.D)(j8,function(b){b(a)}),j8.length=0);
b&&!a?g.yG("yt-remote-connection-change",!1):!b&&a&&g.yG("yt-remote-connection-change",!0)},p8=function(){var a=g.HH();
if(!a)return null;var b=k8().De();return l6(b,a)},v8=function(a,b){r8()&&r8();
oHa(a.id);var c=new a8(i8,a,q8());c.connect(b,pHa());c.subscribe("beforeDisconnect",function(a){g.yG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){s8()&&w8(null)});
w8(c)},jHa=function(){var a=p8();
a?(m8("Resume connection to: "+h6(a)),v8(a,0)):(q6(),OGa(),m8("Skipping connecting because no session screen found."))},gHa=function(){var a=q8();
if(g.Xb(a)){a=o6();var b=g.FH("yt-remote-session-name")||"",c=g.FH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.ta("yt.mdx.remote.channelParams_",a,void 0)}},q8=function(){return g.y("yt.mdx.remote.channelParams_")||{}},iHa=function(a){a?(g.EH("yt-remote-session-app",a.app),g.EH("yt-remote-session-name",a.name)):(g.GH("yt-remote-session-app"),g.GH("yt-remote-session-name"));
g.ta("yt.mdx.remote.channelParams_",a,void 0)},z8=function(a,b,c){g.M.call(this);
this.D=a;this.A=b;this.B=new g.eG(this);g.O(this,this.B);this.B.R(b,"onCaptionsTrackListChanged",this.UT);this.B.R(b,"captionschanged",this.yS);this.B.R(b,"captionssettingschanged",this.AG);this.B.R(b,"videoplayerreset",this.Dq);this.B.R(b,"mdxautoplaycancel",this.yK);this.U=this.B.R(b,"onVolumeChange",this.AE);this.H=!1;this.o=c;c.subscribe("proxyStateChange",this.PE,this);c.subscribe("remotePlayerChange",this.un,this);c.subscribe("remoteQueueChange",this.Dq,this);c.subscribe("autoplayUpNext",this.mE,
this);c.subscribe("previousNextChange",this.ME,this);c.subscribe("nowAutoplaying",this.EE,this);c.subscribe("autoplayDismissed",this.lE,this);this.suggestion=null;this.J=new g.oP(64);this.C=new g.Fu(this.wG,500,this);g.O(this,this.C);this.F=new g.Fu(this.xG,1E3,this);g.O(this,this.F);this.L=new y6(this.aY,0,this);g.O(this,this.L);this.G={};this.M=new g.Fu(this.aH,1E3,this);g.O(this,this.M);this.K=new g.zl(this.xQ,1E3,this);g.O(this,this.K);this.O=g.A;this.AG();this.Dq();this.un()},A8=function(a,b){var c=
a.D,d=a.A.getVideoData().lengthSeconds;
c.J=b||0;c.player.V("progresssync",b,d)},qHa=function(a){A8(a,0);
a.C.stop();B8(a,new g.oP(64))},D8=function(a,b){if(C8(a)&&!a.H){var c=null;
b&&(c={style:a.A.bj()},g.ec(c,b));a.o.kG(a.A.getVideoData(1).videoId,c);a.G=V7(a.o).o}},E8=function(a,b){var c=a.A.qg();
if(c){var d=c.Be();var e=c.listId.toString()}var f=a.A.getVideoData(1);c=a.o;var k=f.videoId,l=d;d=f.playerParams;var m=f.jk;f=$Ea(f);var n=V7(c);l=l||0;var p={videoId:k,currentIndex:l};R7(n,k,l);g.u(b)&&(P7(n,b),p.currentTime=b);g.u(e)&&(p.listId=e);null!=d&&(p.playerParams=d);null!=m&&(p.clickTrackingParams=m);null!=f&&(p.locationInfo=g.Ig(f));Z7(c,"setPlaylist",p);e||X7(c,n);B8(a,new g.oP(1))},rHa=function(a,b){if(b){var c=a.A.Cc("captions","tracklist",{NB:1});
c&&c.length?(a.A.Yd("captions","track",b),a.H=!1):(a.A.Bk("captions"),a.H=!0)}else a.A.Yd("captions","track",{})},C8=function(a){return V7(a.o).videoId==a.A.getVideoData(1).videoId},B8=function(a,b){a.F.stop();
var c=a.J;if(!g.uP(c,b)){var d=g.W(b,2);d!=g.W(a.J,2)&&g.JT(a.A,d);a.J=b;sHa(a.D,c,b)}},F8=function(a){g.V.call(this,{I:"div",
N:"ytp-remote",P:[{I:"div",N:"ytp-remote-display-status",P:[{I:"div",N:"ytp-remote-display-status-icon",P:[g.nsa()]},{I:"div",N:"ytp-remote-display-status-text",da:"{{statustext}}"}]}]});this.B=new g.IU(this,250);g.O(this,this.B);this.C=a;this.R(a,"presentingplayerstatechange",this.D);tHa(this,g.FT(a))},tHa=function(a,b){if(3==a.C.Sa()){var c={RECEIVER_NAME:a.C.Cc("remote","currentReceiver").name};
c=g.W(b,128)?g.AU("Error on $RECEIVER_NAME",c):b.sb()||g.W(b,4)?g.AU("Playing on $RECEIVER_NAME",c):g.AU("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.B.show()}else a.B.hide()},G8=function(a,b){g.iY.call(this,"Play on",0,a,b);
this.B=a;this.J={};this.R(a,"onMdxReceiversChange",this.L);this.R(a,"presentingplayerstatechange",this.L);this.L()},H8=function(a){g.jU.call(this,a);
this.A={key:j6(),name:"This computer"};this.C=null;this.D=[];this.K=this.o=null;this.H=[this.A];this.B=this.A;this.F=new g.oP(64);this.J=0;this.G=-1;if(!g.tN(g.X(this.player))){a=this.player;var b=g.rI(a);b&&(b=b.cn())&&(b=new G8(a,b),g.O(this,b));b=new F8(a);g.O(this,b);g.ZT(a,b.element,4)}},sHa=function(a,b,c){a.F=c;
a.player.V("presentingplayerstatechange",new g.zP(c,b))},I8=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)u8();
else{a.B=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.qg();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Oa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.jk,index:Math.max(a.player.QC(),0),currentTime:0==f?void 0:f};(d=$Ea(d))&&(c.locationInfo=d);d=c}else d=null;m8("Connecting to: "+g.Ig(b));"cast-selector-receiver"==b.key?(o8(d||null),J7()?G7().setLaunchParams(d||
null):E7("setLaunchParams called before ready.")):!d&&x8()&&l8()==b.key?g.yG("yt-remote-connection-change",!0):(u8(),o8(d||null),d=k8().De(),(d=l6(d,b.key))&&v8(d,1))}},IFa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},I6={"'":"\\'"},uHa={},fFa={ZZ:"atp",E4:"ska",V3:"que",j3:"mus",A4:"sus",m1:"dsp"};
e6.prototype.To=function(){var a=new e6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.B=this.B;a.A=this.A;a.o=this.o};
var r6,n6="",v6=s6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",AFa=s6("loadCastFramework")||s6("loadCastApplicationFramework"),KGa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.C(y6,g.M);g.h=y6.prototype;g.h.wL=function(a){this.C=arguments;this.o=!1;this.Ga?this.B=(0,g.H)()+this.Dd:this.Ga=g.Dg(this.D,this.Dd)};
g.h.stop=function(){this.Ga&&(g.Eg(this.Ga),this.Ga=null);this.B=null;this.o=!1;this.C=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.C)))};
g.h.X=function(){this.stop();y6.fa.X.call(this)};
g.h.xL=function(){this.B?(this.Ga=g.Dg(this.D,this.B-(0,g.H)()),this.B=null):(this.Ga=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.C)))};z6.prototype.stringify=function(a){return g.x.JSON.stringify(a,void 0)};
z6.prototype.parse=function(a){return g.x.JSON.parse(a,void 0)};g.h=A6.prototype;g.h.Ii=null;g.h.Pf=!1;g.h.ql=null;g.h.Wx=null;g.h.Uk=null;g.h.Zj=null;g.h.yh=null;g.h.Zh=null;g.h.lj=null;g.h.Vc=null;g.h.On=0;g.h.Qf=null;g.h.Gr=null;g.h.zh=null;g.h.pm=-1;g.h.QF=!0;g.h.ri=!1;g.h.Xt=0;g.h.Rq=null;var GFa={},D6={};g.h=A6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.bX=function(a){a=a.target;var b=this.Rq;b&&3==g.Nx(a)?b.im():this.lH(a)};
g.h.lH=function(a){try{if(a==this.Vc)a:{var b=g.Nx(this.Vc),c=this.Vc.A,d=this.Vc.getStatus();if(g.Jd&&!g.sc(10)||g.Ld&&!g.rc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.rf&&!g.Rx(this.Vc))break a;this.ri||4!=b||7==c||(8==c||0>=d?this.o.If(3):this.o.If(2));K6(this);var e=this.Vc.getStatus();this.pm=e;var f=g.Rx(this.Vc);(this.Pf=200==e)?(4==b&&G6(this),this.D?(HFa(this,b,f),g.rf&&this.Pf&&3==b&&(this.Y.W(this.A,"tick",this.YW),this.A.start())):F6(this,f),this.Pf&&!this.ri&&(4==b?this.o.Bq(this):
(this.Pf=!1,C6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.zh=3,E6(13)):(this.zh=0,E6(14)),G6(this),H6(this))}}catch(k){this.Vc&&g.Rx(this.Vc)}finally{}};
g.h.YW=function(){var a=g.Nx(this.Vc),b=g.Rx(this.Vc);this.On<b.length&&(K6(this),HFa(this,a,b),this.Pf&&4!=a&&C6(this))};
g.h.eW=function(a){J6((0,g.B)(this.dW,this,a),0)};
g.h.dW=function(a){this.ri||(K6(this),F6(this,a),C6(this))};
g.h.YE=function(a){J6((0,g.B)(this.cW,this,a),0)};
g.h.cW=function(a){this.ri||(G6(this),this.Pf=a,this.o.Bq(this),this.o.If(4))};
g.h.cancel=function(){this.ri=!0;G6(this)};
g.h.uW=function(){this.ql=null;var a=(0,g.H)();0<=a-this.Wx?(2!=this.Zj&&this.o.If(3),G6(this),this.zh=2,E6(18),H6(this)):KFa(this,this.Wx-a)};g.h=NFa.prototype;g.h.Vt=null;g.h.Je=null;g.h.Sq=!1;g.h.gB=null;g.h.hp=null;g.h.Qu=null;g.h.Wt=null;g.h.bf=null;g.h.Og=-1;g.h.lm=null;g.h.yl=null;g.h.connect=function(a){this.Wt=a;a=M6(this.o,null,this.Wt);E6(3);this.gB=(0,g.H)();var b=this.o.H;null!=b?(this.lm=b[0],(this.yl=b[1])?(this.bf=1,OFa(this)):(this.bf=2,O6(this))):(d6(a,"MODE","init"),this.Je=new A6(this,void 0,void 0,void 0),this.Je.Ii=this.Vt,B6(this.Je,a,!1,null,!0),this.bf=0)};
g.h.zK=function(a){if(a)this.bf=2,O6(this);else{E6(4);var b=this.o;b.cg=b.oh.Og;V6(b,9)}a&&this.If(2)};
g.h.jt=function(a){return this.o.jt(a)};
g.h.abort=function(){this.Je&&(this.Je.cancel(),this.Je=null);this.Og=-1};
g.h.fB=function(){return!1};
g.h.QE=function(a,b){this.Og=a.pm;if(0==this.bf)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.cg=this.Og;V6(c,2);return}this.lm=c[0];this.yl=c[1]}else c=this.o,c.cg=this.Og,V6(c,2);else if(2==this.bf)if(this.Sq)E6(7),this.Qu=(0,g.H)();else if("11111"==b){if(E6(6),this.Sq=!0,this.hp=(0,g.H)(),c=this.hp-this.gB,!g.Jd||g.sc(10)||500>c)this.Og=200,this.Je.cancel(),E6(12),N6(this.o,this,!0)}else E6(8),this.hp=this.Qu=(0,g.H)(),this.Sq=!1};
g.h.Bq=function(){this.Og=this.Je.pm;if(this.Je.Pf)0==this.bf?this.yl?(this.bf=1,OFa(this)):(this.bf=2,O6(this)):2==this.bf&&((!g.Jd||g.sc(10)?!this.Sq:200>this.Qu-this.hp)?(E6(11),N6(this.o,this,!1)):(E6(12),N6(this.o,this,!0)));else{0==this.bf?E6(9):2==this.bf&&E6(10);var a=this.o;a.cg=this.Og;V6(a,2)}};
g.h.Fn=function(){return this.o.Fn()};
g.h.isActive=function(){return this.o.isActive()};
g.h.If=function(a){this.o.If(a)};g.h=P6.prototype;g.h.Ol=null;g.h.ke=null;g.h.yc=null;g.h.Ut=null;g.h.lp=null;g.h.Fz=null;g.h.Ap=null;g.h.ln=0;g.h.RR=0;g.h.Cd=null;g.h.sh=null;g.h.Cg=null;g.h.wi=null;g.h.oh=null;g.h.Dr=null;g.h.sk=-1;g.h.ZB=-1;g.h.cg=-1;g.h.Pj=0;g.h.Ej=0;g.h.ti=8;var W6=new g.Rf;g.C(QFa,g.pf);g.C(RFa,g.pf);g.C(SFa,g.pf);g.h=P6.prototype;g.h.connect=function(a,b,c,d,e){E6(0);this.Ut=b;this.Ol=c||{};d&&g.u(e)&&(this.Ol.OSID=d,this.Ol.OAID=e);this.F?(J6((0,g.B)(this.Zz,this,a),100),WFa(this)):this.Zz(a)};
g.h.Zz=function(a){this.oh=new NFa(this);this.oh.Vt=null;this.oh.A=this.D;this.oh.connect(a)};
g.h.fB=function(){return 0==this.o};
g.h.WE=function(a){this.sh=null;ZFa(this,a)};
g.h.VE=function(){this.Cg=null;this.yc=new A6(this,this.B,"rpc",this.G);this.yc.Ii=null;this.yc.Xt=0;var a=this.Fz.clone();g.gn(a,"RID","rpc");g.gn(a,"SID",this.B);g.gn(a,"CI",this.Dr?"0":"1");g.gn(a,"AID",this.sk);Q6(this,a);if(!g.Jd||g.sc(10))g.gn(a,"TYPE","xmlhttp"),B6(this.yc,a,!0,this.Ap,!1);else{g.gn(a,"TYPE","html");var b=this.yc,c=!!this.Ap;b.Zj=3;b.yh=c6(a.clone());JFa(b,c)}};
g.h.QE=function(a,b){if(0!=this.o&&(this.yc==a||this.ke==a))if(this.cg=a.pm,this.ke==a&&3==this.o)if(7<this.ti){try{var c=this.D.parse(b)}catch(f){c=null}if(g.wa(c)&&3==c.length)if(0==c[0])a:{if(!this.Cg){if(this.yc)if(this.yc.Uk+3E3<this.ke.Uk)S6(this),this.yc.cancel(),this.yc=null;else break a;U6(this);E6(19)}}else this.ZB=c[1],0<this.ZB-this.sk&&37500>c[2]&&this.Dr&&0==this.Ej&&!this.wi&&(this.wi=J6((0,g.B)(this.tS,this),6E3));else V6(this,11)}else b!=uHa.b0.o&&V6(this,11);else if(this.yc==a&&
S6(this),!g.F(b)){c=this.D.parse(b);g.wa(c);for(var d=0;d<c.length;d++){var e=c[d];this.sk=e[0];e=e[1];2==this.o?"c"==e[0]?(this.B=e[1],this.Ap=e[2],e=e[3],null!=e?this.ti=e:this.ti=6,this.o=3,this.Cd&&this.Cd.Rz(),this.Fz=M6(this,this.Fn()?this.Ap:null,this.Ut),$Fa(this)):"stop"==e[0]&&V6(this,7):3==this.o&&("stop"==e[0]?V6(this,7):"noop"!=e[0]&&this.Cd&&this.Cd.Qz(e),this.Ej=0)}}};
g.h.tS=function(){null!=this.wi&&(this.wi=null,this.yc.cancel(),this.yc=null,U6(this),E6(20))};
g.h.Bq=function(a){if(this.yc==a){S6(this);this.yc=null;var b=2}else if(this.ke==a)this.ke=null,b=1;else return;this.cg=a.pm;if(0!=this.o)if(a.Pf)1==b?(b=(0,g.H)()-a.Uk,W6.dispatchEvent(new RFa(W6,a.lj?a.lj.length:0,b,this.Pj)),R6(this),this.C.length=0):$Fa(this);else{var c=a.zh,d;if(!(d=3==c||7==c||0==c&&0<this.cg)){if(d=1==b)this.ke||this.sh||1==this.o||2<=this.Pj?d=!1:(this.sh=J6((0,g.B)(this.WE,this,a),aGa(this,this.Pj)),this.Pj++,d=!0);d=!(d||2==b&&U6(this))}if(d)switch(c){case 1:V6(this,5);
break;case 4:V6(this,10);break;case 3:V6(this,6);break;case 7:V6(this,12);break;default:V6(this,2)}}};
g.h.XK=function(a){if(!g.Ma(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.QX=function(a){a?E6(2):(E6(1),bGa(this,8))};
g.h.jt=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.Hx;a.H=!1;return a};
g.h.isActive=function(){return!!this.Cd&&this.Cd.isActive(this)};
g.h.If=function(a){W6.dispatchEvent(new SFa(W6,a))};
g.h.Fn=function(){return!(!g.Jd||g.sc(10))};
g.h=cGa.prototype;g.h.Rz=function(){};
g.h.Qz=function(){};
g.h.Pz=function(){};
g.h.Qs=function(){};
g.h.NA=function(){return{}};
g.h.isActive=function(){return!0};g.C(X6,g.M);g.h=X6.prototype;g.h.VV=function(){this.Dd=Math.min(3E5,2*this.Dd);this.B();this.A&&this.start()};
g.h.start=function(){var a=this.Dd+15E3*Math.random();g.Gu(this.o,a);this.A=(0,g.H)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Dd=5E3};g.C(Y6,cGa);g.h=Y6.prototype;g.h.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.h.ce=function(a){return this.B.ce(a)};
g.h.V=function(a,b){return this.B.V.apply(this.B,arguments)};
g.h.dispose=function(){this.K||(this.K=!0,g.nf(this.B),fGa(this),g.nf(this.A),this.A=null)};
g.h.ia=function(){return this.K};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.J="";this.A.stop();this.D=a||null;this.C=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new P6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.M),e=this.o;e&&(e.Cd=null);d.Cd=this;this.o=d;e?this.o.connect(a,b,this.F,e.B,e.sk):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):Z6(this)&&XFa(this.o,c)};
g.h.Rz=function(){this.A.reset();this.D=null;this.C=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)XFa(this.o,a[b])}this.V("handlerOpened")};
g.h.Pz=function(a){var b=2==a&&401==this.o.cg;4==a||b||this.A.start();this.V("handlerError",a)};
g.h.Qs=function(a){if(!this.A.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.NA=function(){var a={v:2};this.J&&(a.gsessionid=this.J);0!=this.C&&(a.ui=""+this.C);0!=this.H&&(a.ui=""+this.H);this.D&&g.ec(a,this.D);return a};
g.h.Qz=function(a){"S"==a[0]?this.J=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),VFa(this.o)):this.V("handlerMessage",new dGa(a[0],a[1]))};
g.h.vY=function(){this.A.isActive();var a=this.o,b=0;a.yc&&b++;a.ke&&b++;0!=b||this.connect(this.D,this.C)};$6.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
$6.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
$6.prototype.D=function(a){a(Error("request timed out"))};var nGa=(0,g.H)(),c7=null,f7=Array(50),e7=-1,g7=!1;g.C(h7,g.hG);h7.prototype.De=function(){return this.o};
h7.prototype.contains=function(a){return!!k6(this.o,a)};
h7.prototype.get=function(a){return a?l6(this.o,a):null};
h7.prototype.info=function(a){d7(this.G,a)};g.C(i7,g.hG);var vHa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=i7.prototype;g.h.start=function(){!this.o&&(0,window.isNaN)(this.Ga)&&this.rH()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);(0,window.isNaN)(this.Ga)||(g.BE(this.Ga),this.Ga=window.NaN)};
g.h.X=function(){this.stop();i7.fa.X.call(this)};
g.h.rH=function(){this.Ga=window.NaN;this.o=g.QE(a7(this.F,"/pairing/get_screen"),{method:"POST",Tb:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.B)(this.xY,this),onError:(0,g.B)(this.wY,this),Id:(0,g.B)(this.yY,this)})};
g.h.xY=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.C;this.V("pairingComplete",new f6(c))};
g.h.wY=function(a){this.o=null;a.status&&404==a.status?this.A>=vHa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=vHa[this.A],this.Ga=g.zE((0,g.B)(this.rH,this),a),this.A++):this.V("pairingFailed",Error("Server error "+a.status))};
g.h.yY=function(){this.o=null;this.V("pairingFailed",Error("Server not responding"))};g.C(k7,h7);g.h=k7.prototype;g.h.start=function(){j7(this)&&this.V("screenChange");!g.FH("yt-remote-lounge-token-expiration")&&rGa(this);g.BE(this.A);this.A=g.zE((0,g.B)(this.start,this),1E4)};
g.h.add=function(a,b){j7(this);oGa(this,a);l7(this,!1);this.V("screenChange");b(a);a.token||rGa(this)};
g.h.remove=function(a,b){var c=j7(this);qGa(this,a)&&(l7(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.h.zr=function(a,b,c,d){var e=j7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,l7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.h.X=function(){g.BE(this.A);k7.fa.X.call(this)};
g.h.LL=function(a){j7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}l7(this,!b);b&&d7(this.G,"Missed "+b+" lounge tokens.")};
g.h.KL=function(a){d7(this.G,"Requesting lounge tokens failed: "+a)};g.C(n7,g.hG);g.h=n7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.FH("yt-remote-fast-check-period")||"0",10);(this.C=(0,g.H)()-144E5<a?0:a)?p7(this):(this.C=(0,g.H)()+3E5,g.EH("yt-remote-fast-check-period",this.C),this.Uw())};
g.h.isEmpty=function(){return g.Xb(this.o)};
g.h.update=function(){m7("Updating availability on schedule.");var a=this.F(),b=g.Hb(this.o,function(b,d){return b&&!!l6(a,d)},this);
o7(this,b)};
g.h.X=function(){g.BE(this.B);this.B=window.NaN;this.A&&(this.A.abort(),this.A=null);n7.fa.X.call(this)};
g.h.Uw=function(){g.BE(this.B);this.B=window.NaN;this.A&&this.A.abort();var a=uGa(this);if(g.Mb(a)){var b=a7(this.D,"/pairing/get_screen_availability");this.A=b7(this.D,b,{lounge_token:g.Pb(a).join(",")},(0,g.B)(this.CV,this,a),(0,g.B)(this.BV,this))}else o7(this,{}),p7(this)};
g.h.CV=function(a,b){this.A=null;var c=g.Pb(uGa(this));if(g.eb(c,g.Pb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;o7(this,d);p7(this)}else this.sc("Changing Screen set during request."),this.Uw()};
g.h.BV=function(a){this.sc("Screen availability failed: "+a);this.A=null;p7(this)};
g.h.sc=function(a){d7("OnlineScreenService",a)};g.C(q7,h7);g.h=q7.prototype;g.h.start=function(){this.B.start();this.A.start();this.o.length&&(this.V("screenChange"),this.A.isEmpty()||this.V("onlineScreenChange"))};
g.h.add=function(a,b,c){this.B.add(a,b,c)};
g.h.remove=function(a,b,c){this.B.remove(a,b,c);this.A.update()};
g.h.zr=function(a,b,c,d){this.B.contains(a)?this.B.zr(a,b,c,d):(a="Updating name of unknown screen: "+a.name,d7(this.G,a),d(Error(a)))};
g.h.De=function(a){return a?this.o:g.Ua(this.o,(0,g.Yd)(this.C,function(a){return!this.contains(a)},this))};
g.h.sH=function(){return(0,g.Yd)(this.De(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.tH=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new i7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.B)(function(a){g.nf(f);d(r7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.nf(f);e(a)});
f.start();return(0,g.B)(f.stop,f)};
g.h.AY=function(a,b,c,d){g.QE(a7(this.F,"/pairing/get_screen"),{method:"POST",Tb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.B)(function(a,d){var e=new f6(d.screen||{});if(!e.name||yGa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);yGa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(r7(this,e))},this),
onError:(0,g.B)(function(a){d(Error("pairing request failed: "+a.status))},this),
Id:(0,g.B)(function(){d(Error("pairing request timed out."))},this)})};
g.h.X=function(){g.nf(this.B);g.nf(this.A);q7.fa.X.call(this)};
g.h.ZL=function(){zGa(this);this.V("screenChange");this.A.update()};
q7.prototype.dispose=q7.prototype.dispose;g.C(t7,g.hG);g.h=t7.prototype;g.h.Cq=function(a){this.B=a;this.V("sessionScreen",this.B)};
g.h.Ie=function(a){this.ia()||(a&&u7(this,""+a),this.B=null,this.V("sessionScreen",null))};
g.h.info=function(a){d7(this.M,a)};
g.h.vH=function(){return null};
g.h.hx=function(a){var b=this.A;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.B)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.B)(function(){u7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.X=function(){this.hx("");t7.fa.X.call(this)};g.C(v7,t7);g.h=v7.prototype;g.h.gx=function(a){if(this.o){if(this.o==a)return;u7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);BGa(this)};
g.h.uk=function(a){this.info("launchWithParams no-op for Cast: "+g.Ig(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.B)(function(){this.Ie()},this),(0,g.B)(function(){this.Ie(Error("Failed to stop receiver app."))},this)):this.Ie(Error("Stopping cast device witout session."))};
g.h.hx=g.A;g.h.X=function(){this.info("disposeInternal");g.BE(this.C);this.C=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;v7.fa.X.call(this)};
g.h.HW=function(a,b){if(!this.ia())if(b){var c=g.Bx(b);if(g.za(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Ig(c));switch(d){case "mdxSessionStatus":AGa(this,c.screenId);break;default:u7(this,"Unknown youtube message: "+d)}}else u7(this,"Unable to parse message.")}else u7(this,"No data in message.")};
g.h.VA=function(a,b,c,d){xGa(this.J,this.A.label,a,this.A.friendlyName,(0,g.B)(function(e){e?b(e):0<=d?(u7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.zE((0,g.B)(this.VA,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.vH=function(){return this.o};
g.h.BY=function(a){this.ia()||a||(u7(this,"Cast session died."),this.Ie())};g.C(w7,t7);g.h=w7.prototype;g.h.gx=function(a){this.C=a;this.C.addUpdateListener(this.L)};
g.h.uk=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.A;g.BE(this.F);this.C?this.C.stop((0,g.B)(this.Ie,this,null),(0,g.B)(this.Ie,this,"Failed to stop DIAL device.")):this.Ie()};
g.h.X=function(){this.o();this.o=g.A;g.BE(this.F);this.C&&this.C.removeUpdateListener(this.L);this.C=null;w7.fa.X.call(this)};
g.h.EY=function(a){this.ia()||a||(u7(this,"DIAL session died."),this.o(),this.o=g.A,this.Ie())};
g.h.Au=function(a){this.K=j6();if(this.D){var b=new window.chrome.cast.DialLaunchResponse(!0,DGa(this));a(b);CGa(this)}else this.G=(0,g.B)(function(){g.BE(this.F);this.G=g.A;this.F=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,DGa(this));a(b);CGa(this)},this),this.F=g.zE((0,g.B)(function(){this.G()},this),100)};
g.h.nN=function(a,b,c){xGa(this.J,this.H.receiver.label,a,this.A.friendlyName,(0,g.B)(function(a){a&&a.token?(this.Cq(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Au(b,c)},this),(0,g.B)(function(a){u7(this,"Failed to get DIAL screen: "+a);
this.Au(b,c)},this))};g.C(x7,t7);x7.prototype.stop=function(){this.Ie()};
x7.prototype.gx=g.A;x7.prototype.uk=function(){g.BE(this.o);this.o=window.NaN;var a=l6(this.J.De(),this.A.label);a?this.Cq(a):this.Ie(Error("No such screen"))};
x7.prototype.X=function(){g.BE(this.o);this.o=window.NaN;x7.fa.X.call(this)};g.C(y7,g.hG);g.h=y7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.B)(this.SE,this),(0,g.B)(this.lV,this),d,e);c.customDialLaunchCallback=(0,g.B)(this.eT,this);window.chrome.cast.initialize(c,
(0,g.B)(function(){this.ia()||(window.chrome.cast.addReceiverActionListener(this.C),kGa(),this.A.subscribe("onlineScreenChange",(0,g.B)(this.uH,this)),this.B=FGa(this),window.chrome.cast.setCustomReceivers(this.B,g.A,(0,g.B)(function(a){this.sc("Failed to set initial custom receivers: "+g.Ig(a))},this)),this.V("yt-remote-cast2-availability-change",A7(this)),b(!0))},this),(0,g.B)(function(a){this.sc("Failed to initialize API: "+g.Ig(a));
b(!1)},this))};
g.h.zX=function(a,b){z7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.B;if(!a||c&&c.id!=a)z7("Unsetting old screen status: "+this.o.A.friendlyName),B7(this,null)}if(a&&b){if(!this.o){c=l6(this.A.De(),a);if(!c){z7("setConnectedScreenStatus: Unknown screen.");return}var d=EGa(this,c);d||(z7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.B.push(d),
window.chrome.cast.setCustomReceivers(this.B,g.A,(0,g.B)(function(a){this.sc("Failed to set initial custom receivers: "+g.Ig(a))},this)));
z7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);B7(this,new x7(this.A,d),!0)}this.o.hx(b)}else z7("setConnectedScreenStatus: no screen.")};
g.h.AX=function(a){this.ia()?this.sc("Setting connection data on disposed cast v2"):this.o?this.o.uk(a):this.sc("Setting connection data without a session")};
g.h.DY=function(){this.ia()?this.sc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),B7(this,null)):z7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.B)(this.SE,this),(0,g.B)(this.HV,this))};
g.h.X=function(){this.A.unsubscribe("onlineScreenChange",(0,g.B)(this.uH,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.C);g.Sa(g.y("yt.mdx.remote.debug.handlers_")||[],hGa);g.nf(this.o);y7.fa.X.call(this)};
g.h.sc=function(a){d7("Controller",a)};
g.h.TE=function(a,b){this.o==a&&(b||B7(this,null),this.V("yt-remote-cast2-session-change",b))};
g.h.hV=function(a,b){if(!this.ia())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),z7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)z7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{z7("onReceiverAction_: Casting to active receiver.");this.o.B&&this.V("yt-remote-cast2-session-change",this.o.B);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:B7(this,
new x7(this.A,a));break;case window.chrome.cast.ReceiverType.DIAL:B7(this,new w7(this.A,a,this.F));break;case window.chrome.cast.ReceiverType.CAST:B7(this,new v7(this.A,a));break;default:this.sc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.sc("Stopping receiver w/o session: "+a.friendlyName)}else this.sc("onReceiverAction_ called without receiver.")};
g.h.eT=function(a){if(this.ia())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.sc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.sc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.o.B)return z7("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.o.B),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.sc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);B7(this,new w7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.B)(b.nN,b,(b.H.extraData||{}).screenId||null)):new window.Promise((0,g.B)(b.Au,b))};
g.h.SE=function(a){if(!this.ia()){z7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)z7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),B7(this,new v7(this.A,b),!0);else{this.sc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=l6(this.A.De(),c.label);
d&&g6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(z7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.nf(this.o),this.o=new v7(this.A,b),this.o.subscribe("sessionScreen",(0,g.B)(this.TE,this,this.o)),this.o.uk(null));this.o.gx(a)}}};
g.h.CY=function(){return this.o?this.o.vH():null};
g.h.HV=function(a){this.ia()||(this.sc("Failed to estabilish a session: "+g.Ig(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&B7(this,null))};
g.h.lV=function(a){z7("Receiver availability updated: "+a);if(!this.ia()){var b=A7(this);this.D=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;A7(this)!=b&&this.V("yt-remote-cast2-availability-change",A7(this))}};
g.h.uH=function(){this.ia()||(this.B=FGa(this),z7("Updating custom receivers: "+g.Ig(this.B)),window.chrome.cast.setCustomReceivers(this.B,g.A,(0,g.B)(function(){this.sc("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",A7(this)))};
y7.prototype.setLaunchParams=y7.prototype.AX;y7.prototype.setConnectedScreenStatus=y7.prototype.zX;y7.prototype.stopSession=y7.prototype.DY;y7.prototype.getCastSession=y7.prototype.CY;y7.prototype.requestSession=y7.prototype.requestSession;y7.prototype.init=y7.prototype.init;y7.prototype.dispose=y7.prototype.dispose;var H7=[];g.h=M7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";N7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.gg=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.C=a.seekableStart,this.A=a.seekableEnd,this.H=a.duration,this.J=a.loadedTime,this.B=a.liveIngestionTime,this.D=!(0,window.isNaN)(this.B))};
g.h.sb=function(){return 1==this.playerState};
g.h.isAdPlaying=function(){return 1081==this.playerState};
g.h.getDuration=function(){return this.D?this.H+O7(this):this.H};
g.h.clone=function(){return new M7(S7(this))};g.C(U7,g.hG);g.h=U7.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.A,$7(this,"play")):Z7(this,"play"),Y7(this,1,Q7(V7(this))),this.V("remotePlayerChange")):W7(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.A,$7(this,"pause")):Z7(this,"pause"),Y7(this,2,Q7(V7(this))),this.V("remotePlayerChange")):W7(this,this.pause)};
g.h.qH=function(a){if(1==this.o){if(this.A){var b=V7(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.sb()||3==b.playerState?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.A,$7(this,"seekTo",{newTime:a}))}else Z7(this,"seekTo",{newTime:a});Y7(this,3,a);this.V("remotePlayerChange")}else W7(this,g.Ca(this.qH,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.A,$7(this,"stopVideo")):Z7(this,"stopVideo");var a=V7(this);a.index=-1;a.videoId="";N7(a);X7(this,a);this.V("remotePlayerChange")}else W7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=V7(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.B)(function(){d7("CP","set receiver volume: "+d)},this),(0,g.B)(function(){this.sc("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.B)(function(){d7("CP","set receiver muted: "+b)},this),(0,g.B)(function(){this.sc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);Z7(this,"setVolume",e)}c.muted=b;c.volume=a;X7(this,c)}else W7(this,g.Ca(this.setVolume,a,b))};
g.h.kG=function(a,b){if(1==this.o){var c=V7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Ig(b.style),g.ec(d,c.o));Z7(this,"setSubtitlesTrack",d);X7(this,c)}else W7(this,g.Ca(this.kG,a,b))};
g.h.fy=function(a,b){if(1==this.o){Z7(this,"setAudioTrack",{videoId:a,audioTrackId:b.Nb.id});var c=V7(this);c.audioTrackId=b.Nb.id;X7(this,c)}else W7(this,g.Ca(this.fy,a,b))};
g.h.pH=function(a,b){if(1==this.o){if(a&&b){var c=V7(this);R7(c,a,b);X7(this,c)}Z7(this,"previous")}else W7(this,g.Ca(this.pH,a,b))};
g.h.oH=function(a,b){if(1==this.o){if(a&&b){var c=V7(this);R7(c,a,b);X7(this,c)}Z7(this,"next")}else W7(this,g.Ca(this.oH,a,b))};
g.h.rA=function(){1==this.o?Z7(this,"dismissAutoplay"):W7(this,this.rA)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.V("proxyStateChange",a,this.o)}U7.fa.dispose.call(this)};
g.h.X=function(){SGa(this);this.C=null;this.D.clear();T7(this,null);U7.fa.X.call(this)};
g.h.gy=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.VC(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.cV=function(a,b){this.V(a,b)};
g.h.AS=function(a){if(!a)this.pn(null),T7(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=V7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)d7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,X7(this,b)}};
g.h.pn=function(a){d7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),TGa(this),this.V("remotePlayerChange")};
g.h.zS=function(a){a?(TGa(this),this.V("remotePlayerChange")):this.pn(null)};
g.h.NS=function(){var a=PGa();a&&T7(this,a)};
g.h.sc=function(a){d7("CP",a)};g.C(a8,g.hG);g.h=a8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.u(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.u(k)&&(l.currentIndex=k);c&&(this.jb.listId=c);this.jb.videoId=d;this.jb.index=k||0;this.jb.state=3;P7(this.jb,m);this.C="UNSUPPORTED";b8("Connecting with setPlaylist and params: "+g.Ig(l));this.o.connect({method:"setPlaylist",
params:g.Ig(l)},a,nFa())}else b8("Connecting without params"),this.o.connect({},a,nFa());VGa(this)};
g.h.dispose=function(){this.ia()||(this.V("beforeDispose"),c8(this,3));a8.fa.dispose.call(this)};
g.h.X=function(){d8(this);f8(this);e8(this);g.BE(this.J);this.J=window.NaN;g.BE(this.K);this.K=window.NaN;this.B=null;g.SF(this.U);this.U.length=0;this.o.dispose();a8.fa.X.call(this);this.C=this.G=this.A=this.jb=this.o=null};
g.h.BL=function(){this.F(2)};
g.h.ES=function(){b8("Channel opened");this.O&&(this.O=!1,e8(this),this.M=g.zE((0,g.B)(function(){b8("Timing out waiting for a screen.");this.F(1)},this),15E3));
rFa(eGa(this.o),this.ba)};
g.h.BS=function(){b8("Channel closed");(0,window.isNaN)(this.D)?q6(!0):q6();this.dispose()};
g.h.CS=function(a){q6();(0,window.isNaN)(this.H())?(b8("Channel error: "+a+" without reconnection"),this.dispose()):(this.O=!0,b8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),c8(this,2))};
g.h.DS=function(a){a.params?b8("Received: action="+a.action+", params="+g.Ig(a.params)):b8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Bx(a.params.devices);this.A=(0,g.J)(a,function(a){return new e6(a)});
a=!!g.Ha(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
YGa(this,a);break;case "loungeScreenDisconnected":g.Ta(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
YGa(this,!1);break;case "remoteConnected":var b=new e6(g.Bx(a.params.device));g.Ha(this.A,function(a){return b?a.id==b.id:!1})||g.Pa(this.A,b);
break;case "remoteDisconnected":b=new e6(g.Bx(a.params.device));g.Ta(this.A,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":$Ga(this,a);break;case "nowPlaying":bHa(this,a);break;case "onStateChange":aHa(this,a);break;case "onAdStateChange":cHa(this,a);break;case "onVolumeChanged":dHa(this,a);break;case "onSubtitlesTrackChanged":ZGa(this,a);break;case "nowAutoplaying":eHa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.V("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.V("autoplayModeChange",this.C);"DISABLED"==this.C&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":fHa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:b8("Unrecognized action: "+a.action)}};
g.h.jX=function(){if(this.B){var a=this.B;this.B=null;this.jb.videoId!=a&&g8(this,"getNowPlaying")}};
a8.prototype.subscribe=a8.prototype.subscribe;a8.prototype.unsubscribeByKey=a8.prototype.ce;a8.prototype.ha=function(){var a=3;this.ia()||(a=0,(0,window.isNaN)(this.H())?Z6(this.o)&&(0,window.isNaN)(this.D)&&(a=1):a=2);return a};
a8.prototype.getProxyState=a8.prototype.ha;a8.prototype.F=function(a){b8("Disconnecting with "+a);d8(this);this.V("beforeDisconnect",a);1==a&&q6();fGa(this.o,a);this.dispose()};
a8.prototype.disconnect=a8.prototype.F;a8.prototype.ga=function(){var a=this.jb;this.B&&(a=this.jb.clone(),R7(a,this.B,a.index));return S7(a)};
a8.prototype.getPlayerContextData=a8.prototype.ga;
a8.prototype.na=function(a){var b=new M7(a);b.videoId&&b.videoId!=this.jb.videoId&&(this.B=b.videoId,g.BE(this.J),this.J=g.zE((0,g.B)(this.jX,this),5E3));var c=[];this.jb.listId==b.listId&&this.jb.videoId==b.videoId&&this.jb.index==b.index||c.push("remoteQueueChange");this.jb.playerState==b.playerState&&this.jb.volume==b.volume&&this.jb.muted==b.muted&&Q7(this.jb)==Q7(b)&&g.Ig(this.jb.o)==g.Ig(b.o)||c.push("remotePlayerChange");this.jb.reset(a);(0,g.D)(c,function(a){this.V(a)},this)};
a8.prototype.setPlayerContextData=a8.prototype.na;a8.prototype.Z=function(){var a=this.o.F.id,b=g.Ha(this.A,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
a8.prototype.getOtherConnectedRemoteId=a8.prototype.Z;a8.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.H)():window.NaN};
a8.prototype.getReconnectTimeout=a8.prototype.H;a8.prototype.aa=function(){return this.C||"UNSUPPORTED"};
a8.prototype.getAutoplayMode=a8.prototype.aa;a8.prototype.ca=function(){return this.G||""};
a8.prototype.getAutoplayVideoId=a8.prototype.ca;a8.prototype.wa=function(){if(!(0,window.isNaN)(this.H())){var a=this.o.A;g.Hu(a.o);a.start()}};
a8.prototype.reconnect=a8.prototype.wa;a8.prototype.ka=function(a,b){g8(this,a,b);XGa(this)};
a8.prototype.sendMessage=a8.prototype.ka;g.C(h8,h7);g.h=h8.prototype;g.h.De=function(a){return this.md.$_gs(a)};
g.h.contains=function(a){return!!this.md.$_c(a)};
g.h.get=function(a){return this.md.$_g(a)};
g.h.start=function(){this.md.$_st()};
g.h.add=function(a,b,c){this.md.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.md.$_r(a,b,c)};
g.h.zr=function(a,b,c,d){this.md.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.A.length;a<b;++a)this.md.$_ubk(this.A[a]);this.A.length=0;this.md=null;h8.fa.X.call(this)};
g.h.zY=function(){this.V("screenChange")};
g.h.BU=function(){this.V("onlineScreenChange")};
q7.prototype.$_st=q7.prototype.start;q7.prototype.$_gspc=q7.prototype.AY;q7.prototype.$_gsppc=q7.prototype.tH;q7.prototype.$_c=q7.prototype.contains;q7.prototype.$_g=q7.prototype.get;q7.prototype.$_a=q7.prototype.add;q7.prototype.$_un=q7.prototype.zr;q7.prototype.$_r=q7.prototype.remove;q7.prototype.$_gs=q7.prototype.De;q7.prototype.$_gos=q7.prototype.sH;q7.prototype.$_s=q7.prototype.subscribe;q7.prototype.$_ubk=q7.prototype.ce;var i8=null,j8=null,y8=null,n8=[];g.r(z8,g.M);g.h=z8.prototype;
g.h.X=function(){g.M.prototype.X.call(this);this.C.stop();this.F.stop();this.L.stop();this.O();this.o.unsubscribe("proxyStateChange",this.PE,this);this.o.unsubscribe("remotePlayerChange",this.un,this);this.o.unsubscribe("remoteQueueChange",this.Dq,this);this.o.unsubscribe("autoplayUpNext",this.mE,this);this.o.unsubscribe("previousNextChange",this.ME,this);this.o.unsubscribe("nowAutoplaying",this.EE,this);this.o.unsubscribe("autoplayDismissed",this.lE,this);this.o=this.D=null};
g.h.hD=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(C8(this)){if(!V7(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":V7(this.o).sb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.K.im(c[0],c[1]);break;case "control_subtitles_set_track":D8(this,c[0]);break;case "control_set_audio_track":c=c[0],C8(this)&&this.o.fy(this.A.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.A.getCurrentTime();E8(this,0==c?void 0:c);break;case "control_seek":E8(this,c[0]);break;case "control_subtitles_set_track":D8(this,c[0]);break;case "control_set_audio_track":c=c[0],C8(this)&&this.o.fy(this.A.getVideoData(1).videoId,c)}};
g.h.yS=function(a){this.L.wL(a)};
g.h.aY=function(a){this.hD("control_subtitles_set_track",g.Xb(a)?null:a)};
g.h.AG=function(){var a=this.A.Cc("captions","track");g.Xb(a)||D8(this,a)};
g.h.AE=function(a){if(C8(this)){this.o.unsubscribe("remotePlayerChange",this.un,this);var b=Math.round(a.volume);a=!!a.muted;var c=V7(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.M.start();this.o.subscribe("remotePlayerChange",this.un,this)}};
g.h.UT=function(){g.Xb(this.G)||rHa(this,this.G);this.H=!1};
g.h.PE=function(a,b){this.F.stop();2==b&&this.xG()};
g.h.un=function(){if(C8(this)){this.C.stop();var a=V7(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.D.G=1;break;case 1082:case 1083:this.D.G=0;break;default:this.D.G=-1}switch(a.playerState){case 1081:case 1:B8(this,new g.oP(8));this.wG();break;case 1085:case 3:B8(this,new g.oP(9));break;case 1083:case 0:B8(this,new g.oP(2));this.K.stop();A8(this,this.A.getVideoData().lengthSeconds);break;case 1084:B8(this,new g.oP(4));break;case 2:B8(this,new g.oP(4));A8(this,Q7(a));
break;case -1:B8(this,new g.oP(64));break;case -1E3:B8(this,new g.oP(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=V7(this.o).o;var b=this.G;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.G=a,rHa(this,a));a=V7(this.o);-1==a.volume||Math.round(this.A.getVolume())==a.volume&&this.A.isMuted()==a.muted||this.M.isActive()||this.aH()}else qHa(this)};
g.h.ME=function(){this.A.V("mdxpreviousnextchange")};
g.h.Dq=function(){C8(this)||qHa(this)};
g.h.yK=function(){this.o.rA()};
g.h.mE=function(a){a&&(a=g.QE("/watch_queue_ajax",{method:"GET",dd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.B)(this.hW,this)}))&&(this.O=(0,g.B)(a.abort,a))};
g.h.hW=function(a,b){var c=new g.GO(g.X(this.A),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.A.V("mdxautoplayupnext",c)};
g.h.EE=function(a){(0,window.isNaN)(a)||this.A.V("mdxnowautoplaying",a)};
g.h.lE=function(){this.A.V("mdxautoplaycanceled")};
g.h.xQ=function(a,b){-1==V7(this.o).playerState?E8(this,a):b&&this.o.qH(a)};
g.h.aH=function(){if(C8(this)){var a=V7(this.o);this.B.Ka(this.U);a.muted?this.A.mute():this.A.rg();this.A.setVolume(a.volume);this.U=this.B.R(this.A,"onVolumeChange",this.AE)}};
g.h.wG=function(){this.C.stop();if(!this.o.ia()){var a=V7(this.o);a.sb()&&B8(this,new g.oP(8));A8(this,Q7(a));this.C.start()}};
g.h.xG=function(){this.F.stop();this.C.stop();var a=this.o.C.getReconnectTimeout();2==this.o.o&&!(0,window.isNaN)(a)&&this.F.start()};g.r(F8,g.V);F8.prototype.D=function(a){tHa(this,a.state)};g.r(G8,g.iY);G8.prototype.L=function(){var a=this.B.Cc("remote","receivers");a&&1<a.length&&!this.B.Cc("remote","quickCast")?(this.J=g.gb(a,this.F,this),g.jY(this,(0,g.J)(a,this.F)),a=this.B.Cc("remote","currentReceiver"),this.Hf(this.F(a)),this.enable(!0)):this.enable(!1)};
G8.prototype.F=function(a){return a.key};
G8.prototype.Gf=function(a){return"cast-selector-receiver"==a?"Cast...":this.J[a].name};
G8.prototype.Gd=function(a){g.iY.prototype.Gd.call(this,a);this.B.Yd("remote","currentReceiver",this.J[a]);this.D.Sb()};g.r(H8,g.jU);g.h=H8.prototype;g.h.create=function(){kHa(g.lN(g.X(this.player)));this.D.push(g.uG("yt-remote-before-disconnect",this.uS,this));this.D.push(g.uG("yt-remote-connection-change",this.mV,this));this.D.push(g.uG("yt-remote-receiver-availability-change",this.NE,this));this.D.push(g.uG("yt-remote-auto-connect",this.kV,this));this.D.push(g.uG("yt-remote-receiver-resumed",this.jV,this));this.NE()};
g.h.load=function(){this.player.Av();g.jU.prototype.load.call(this);this.C=new z8(this,this.player,this.o);var a=(a=pHa())?a.currentTime:0;var b=x8()?new U7(s8(),void 0):null;0==a&&b&&(a=Q7(V7(b)));0!=a&&(this.J=a||0,this.player.V("progresssync",a,void 0));sHa(this,this.F,this.F);g.A_(this.player.app,6)};
g.h.unload=function(){this.player.V("mdxautoplaycanceled");this.B=this.A;g.of(this.C,this.o);this.o=this.C=null;g.jU.prototype.unload.call(this);g.A_(this.player.app,5)};
g.h.X=function(){g.vG(this.D);g.jU.prototype.X.call(this)};
g.h.bn=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.hD.apply(this.C,[a].concat(g.ea(c)))};
g.h.rL=function(){return this.loaded?this.C.suggestion:null};
g.h.gg=function(){return this.o?V7(this.o).gg:!1};
g.h.hasNext=function(){return this.o?V7(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.J};
g.h.lQ=function(){var a=V7(this.o),b=this.player.getVideoData();return{allowSeeking:g.X(this.player).experiments.o("web_player_mdx_allow_seeking_change_killswitch")?this.player.Lc():!a.isAdPlaying()&&this.player.Lc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.D?a.B+O7(a):a.B,isPeggedToLive:1>=(a.D?a.A+O7(a):a.A)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.D?a.A+O7(a):a.A,seekableStart:0<a.C?a.C+O7(a):a.C}};
g.h.mQ=function(){this.o&&this.o.oH()};
g.h.nQ=function(){this.o&&this.o.pH()};
g.h.uS=function(a){1==a&&(this.K=this.o?V7(this.o):null)};
g.h.mV=function(){var a=x8()?new U7(s8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.K=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.nf(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.player.getVideoData().videoId&&this.player.OC(a.videoId,Q7(a)));this.player.V("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.NE=function(){this.H=[this.A].concat(mHa());var a=t8()||this.A;I8(this,a);this.player.ya("onMdxReceiversChange")};
g.h.kV=function(){var a=t8();I8(this,a)};
g.h.jV=function(){this.B=t8()};
g.h.kQ=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.H;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?K7():I8(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.H.length&&"cast-selector-receiver"==this.H[1].key?(b&&K7(),!0):!1}};
g.h.oQ=function(){Z7(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Ec=function(){return!1};g.iX.remote=H8;})(_yt_player);
